### ISSUE TITLE
Utilisation avec LaunchMyCraft

### ISSUE THREAD

**Issue by Aeris1One** [MineWeb/Plugin-Auth#3]
Bonjour, j'aimerais savoir si votre plugin peut être utilisé avec l'outil de création de launcher appelé LaunchMyCraft : https://launchmycraft.fr/
Si oui pourriez vous m'expliquer comment l'utiliser ?

Cordialement,
Celemo

**Comment by sadoj-kuro** [comment]
non vue que tu na pas access au source code du launcher
